#!/usr/bin/env bash
#Write a Bash script that displays the time for 12 hours and 59 minutes
HOURS=0
while [ $HOURS -lt 12 ]
do
    echo "Hour: $HOURS"
    MINUTES=1
    while [ $MINUTES -lt 59 ]
    do
        echo $MINUTES
	let MINUTES+=1
    done
 
